### ISSUE TITLE
Una recomendación sobre entornos virtuales

### ISSUE THREAD

**Issue by categulario** [leomtz/personalpage#1]
un entorno virtual contiene el conjunto de dependencias resueltas, binarios y bytecode asociados a ellas. Como tal no es buena idea transportarlo como parte de un repositorio de la misma manera que no es buena idea llevar binarios como parte del código fuente.

Una recomendación, además de añadirlo al .gitignore es añadir un archivo `requirements.txt` que permita la instalación predecible de las dependencias. La instalación se vuelve algo como:

* `virtualenv -p /path/to/right/python/version venv`
* `source venv/bin/activate`
* `pip install -r requirements.txt`

**Comment by leomtz** [comment]
Sugerencias aceptadas. ¡Gracias!
